uns:
  version:
    corpora_schema_version: 1.1.0
    corpora_encoding_version: 0.1.0
  organism: Homo sapiens
  organism_ontology_term_id: NCBITaxon:9606
  layer_descriptions:
    raw: raw
    X: log1p
  publication_doi: https://doi.org/00.0000/2021.01.1.000000
  title: PBMC 3K
obs:
  assay_ontology_term_id: EFO:0008913
  ethnicity_ontology_term_id: unknown
  sex: unknown
  disease_ontology_term_id: PATO:0000461
  tissue_ontology_term_id: UBERON:0000178
  cell_type_ontology_term_id:
    louvain:
      NK: CL:0000623
      Dendritic: CL:0000451
      CD4 T: CL:0000624
      FCGR3A Monocytes: CL:0002396
      Megakaryocytes: CL:0000556
      B: CL:0000236
      CD8 T: CL:0000625
      CD14 Monocytes: CL:0001055
  development_stage_ontology_term_id: HsapDv:0000087  
fixup_gene_symbols:
  X: log1p
  raw: raw
